MovieApp - Retrofit ile REST Web Servis İsteği Yapma
mustafakamber/task-4-solution pull request #1
Opened 2024-04-19 11:38 UTC by mustafakamber

2024-04-28 21:14 UTC, scotoglu requested changes

2024-04-28 21:14 UTC, scotoglu commented on Task4Solution/app/src/main/java/com/mustk/task4solution/ui/movie/view/MovieDetailFragment.kt
> +            detailLoading.visibility = oppositeVisibility
`isVisible = loading` veya `isVisible = !loading` kullanımı olabilir.

2024-04-28 21:14 UTC, scotoglu commented on Task4Solution/app/src/main/java/com/mustk/task4solution/ui/movie/view/MovieListFragment.kt
> +                listRecyclerView.visibility = View.GONE
`isVisible` da kullanılabilir

2024-04-28 21:14 UTC, scotoglu commented on Task4Solution/app/src/main/java/com/mustk/task4solution/ui/movie/viewmodel/MovieListViewModel.kt
> +        job = viewModelScope.launch {
neden Job kullandık? joba gerek olmandan viewModelScope'ta kullanılabilir.

2024-04-28 21:14 UTC, scotoglu commented on Task4Solution/app/src/main/java/com/mustk/task4solution/ui/movie/view/MovieDetailFragment.kt
> +        viewModel.movieDetail.observe(viewLifecycleOwner) { movieDetail ->
`observe` için bir extension var mı yok mu kontrol edebilir misin?

2024-04-28 21:14 UTC, scotoglu commented on Task4Solution/app/src/main/java/com/mustk/task4solution/shared/Resource.kt
> +enum class Status {
enum `Status` shared altında ayrı bir file alınabilir.

2024-04-28 21:14 UTC, scotoglu commented on Task4Solution/app/src/main/java/com/mustk/task4solution/data/model/Response.kt
> +open class Response(
`BaseResponse` olarak isimlendirebiliriz

2024-04-28 21:14 UTC, scotoglu commented on Task4Solution/app/src/main/java/com/mustk/task4solution/data/datasource/MovieDataSource.kt
> +    suspend fun fetchMovieData(@Query(IMDB_ID_QUERY_PARAM) imdbId: String): Resource<Movie>
Bir satır boşluk bırakılabilir

2024-04-28 21:14 UTC, scotoglu commented on Task4Solution/app/src/main/java/com/mustk/task4solution/data/service/MovieService.kt
> +    @GET(SLASH_QUERY_PARAM)
`fetchAllMovieData` sonrası bir satır boşluk bırakılabilir.

2024-05-13 08:20 UTC, iamkurtgoz approved these changes

2024-05-13 12:39 UTC, fatih-ozturk approved these changes

2024-05-13 14:21 UTC, merged